version: "2.1"
services:
  #used to create a docker of mysql , if you prefer to have an external mysql database, you can remove this block
  ############################################################START Mysql Container###############################################################

  mysql:
    container_name: "fs-mysql"
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - fs_net
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql_data_fs:/var/lib/mysql
    command: --init-file /data/application/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 20s
      retries: 10
  ############################################################END MYSQL Container###############################################################

  ############################################################START OF Core APIs###############################################################
  attendance-api:
    container_name: "fs-attendance-api"
    image: livecs/attendanceapi
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_ENV=${ENVIRONMENT}
      - APP_NAME=AttendanceApi
      - SERVER_PORT=8085
      - DB_HOST=${MYSQL_HOSTNAME}
      - DB_DATABASE=attendance
      - DB_USER=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "8085:8085"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  giving-api:
    container_name: "fs-giving-api"
    image: livecs/givingapi
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_ENV=${ENVIRONMENT}
      - APP_NAME=GivingApi
      - SERVER_PORT=8084
      - DB_HOST=${MYSQL_HOSTNAME}
      - DB_DATABASE=giving
      - DB_USER=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "8084:8084"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  membership-api:
    container_name: "fs-membership-api"
    image: livecs/membershipapi
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_ENV=${ENVIRONMENT}
      - APP_NAME=MembershipApi
      - SERVER_PORT=8083
      - DB_HOST=${MYSQL_HOSTNAME}
      - DB_DATABASE=membership
      - DB_USER=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - FILE_STORE=disk
    ports:
      - "8083:8083"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  ############################################################END OF Core APIs#################################################################

  ############################################################START OF CHUMS-APP###############################################################
  chums-app:
    container_name: "fs-chums-app"
    tty: true
    image: livecs/chumsapp
    environment:
      - PORT=3101
      - REACT_APP_ACCESS_API=${PROTOCOL}://${DOMAIN}:${ACCESS_API_PORT}
      - REACT_APP_ATTENDANCE_API=${PROTOCOL}://${DOMAIN}:${ATTENDANCE_API_PORT}
      - REACT_APP_GIVING_API=${PROTOCOL}://${DOMAIN}:${GIVING_API_PORT}
      - REACT_APP_MEMBERSHIP_API=${PROTOCOL}://${DOMAIN}:${MEMBERSHIP_API_PORT}
      - REACT_APP_ACCOUNTS_APP_URL=${PROTOCOL}://${DOMAIN}:${ACCOUNTS_APP_PORT}
      - REACT_APP_CHURCH_APPS_URL=${PROTOCOL}://${DOMAIN}:${CHURCH_APP_PORT}
      - REACT_APP_CONTENT_ROOT=${PROTOCOL}://${DOMAIN}:${CONTENT_PORT}
      - REACT_APP_GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS}
    ports:
      - "3101:3101"
    networks:
      - fs_net

  ############################################################END OF CHUMS-APP###############################################################

  ############################################################Start OF ChurchApps#############################################################

  accounts-app:
    container_name: "fs-accounts-app"
    tty: true
    image: livecs/accountsapp
    environment:
      - PORT=3401
      - REACT_APP_ACCESS_API=${PROTOCOL}://${DOMAIN}:${ACCESS_API_PORT}
      - REACT_APP_GIVING_API=${PROTOCOL}://${DOMAIN}:${GIVING_API_PORT}
      - REACT_APP_MEMBERSHIP_API=${PROTOCOL}://${DOMAIN}:${MEMBERSHIP_API_PORT}
      - REACT_APP_CHUMS_URL=${PROTOCOL}://${DOMAIN}:${CHUMS_APP_PORT}
      - REACT_APP_CHURCH_APPS_URL=${PROTOCOL}://${DOMAIN}:${CHURCH_APP_PORT}
      - REACT_APP_B1_API=${PROTOCOL}://${DOMAIN}:${B1_API_PORT}
      - REACT_APP_B1_URL=${PROTOCOL}://${DOMAIN}:${B1_ADMIN_APP_PORT}
      - REACT_APP_CONTENT_ROOT=${PROTOCOL}://${DOMAIN}:${CONTENT_PORT}
    ports:
      - "3401:3401"
    networks:
      - fs_net

  church-apps-web:
    container_name: "fs-church-apps-web"
    tty: true
    image: livecs/churchappsweb
    environment:
      - PORT=3400
      - REACT_APP_ACCESS_API=${PROTOCOL}://${DOMAIN}:${ACCESS_API_PORT}
      - REACT_APP_ACCOUNTS_APP_URL=${PROTOCOL}://${DOMAIN}:${ACCOUNTS_APP_PORT}
      - REACT_APP_GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS}
    ports:
      - "3400:3400"
    networks:
      - fs_net

  ############################################################END OF ChurchApps#############################################################

  ###############################################################Start OF B1###################################################################
  b1-app:
    container_name: "fs-b1-app"
    tty: true
    image: livecs/b1app
    environment:
      - PORT=3301
      - REACT_APP_NAME=B1App
      - REACT_APP_ACCESS_API=${PROTOCOL}://${DOMAIN}:${ACCESS_API_PORT}
      - REACT_APP_B1_API=${PROTOCOL}://${DOMAIN}:${B1_API_PORT}
      - REACT_APP_CONTENT_ROOT=${PROTOCOL}://${DOMAIN}:${CONTENT_PORT}
      - REACT_APP_CHURCH_APPS_URL=${PROTOCOL}://${DOMAIN}:${CHURCH_APP_PORT}
    ports:
      - "3301:3301"
    networks:
      - fs_net

  ###############################################################END OF B1###################################################################

  ########################################################## content ########################################################################

  content:
    container_name: "fs-content"
    tty: true
    build: ../../../Images/NGINX/Content
    ports:
      - "3402:3402"
    networks:
      - fs_net
    volumes:
      - content:/content

######################################################### End of content ##################################################################

networks:
  fs_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24
volumes:
  mysql_data_fs:
    {
      ,
    }
  content:
    {
      ,
    }
