version: "2.1"
services:

  
  mysql:
    container_name: "mysql"
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: attendance
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: chruser
    ports:
      - "3306:3306"
    networks:
      - dev_net
    volumes:
       - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    mem_limit: 50MB
    mem_reservation: 20MB


  attendance-api:
    container_name: "attendance-api"
    build: ./AttendanceApi
    ports:
      - "8085:8085"
    networks:
      - dev_net
    depends_on:
      mysql:
        condition: service_healthy
    mem_limit: 50MB
    mem_reservation: 20MB

  giving-api:
    container_name: "giving-api"
    build: ./GivingApi
    ports:
      - "8084:8084"
    networks:
      - dev_net
    depends_on:
      mysql:
        condition: service_healthy
    mem_limit: 50MB
    mem_reservation: 20MB

  membership-api:
    container_name: "membership-api"
    build: ./MembershipApi
    ports:
      - "8083:8083"
    networks:
      - dev_net
    depends_on:
      mysql:
        condition: service_healthy
    mem_limit: 50MB
    mem_reservation: 20MB


  access-api:
    container_name: "access-api"
    build: ./AccessApi
    ports:
      - "8082:8082"
    networks:
      - dev_net
    depends_on:
      mysql:
        condition: service_healthy   
    mem_limit: 50MB
    mem_reservation: 20MB

networks:
  dev_net:

volumes: 
  mysql_data : {}