version: "2.1"
services:
  mysql:
    container_name: "fs-mysql"
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - fs_net
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql_data_fs:/var/lib/mysql
    command: --init-file /data/application/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 30s
      timeout: 20s
      retries: 10
    mem_limit: 256MB

  attendance-api:
    container_name: "fs-attendance-api"
    build: ../../../Images/CoreApis/AttendanceApi
    ports:
      - "8085:8085"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  doing-api:
    container_name: "fs-doing-api"
    build: ../../../Images/CoreApis/DoingApi
    ports:
      - "8088:8088"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  giving-api:
    container_name: "fs-giving-api"
    build: ../../../Images/CoreApis/GivingApi
    ports:
      - "8084:8084"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  membership-api:
    container_name: "fs-membership-api"
    build: ../../../Images/CoreApis/MembershipApi
    ports:
      - "8083:8083"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  reporting-api:
    container_name: "fs-reporting-api"
    build: ../../../Images/CoreApis/ReportingApi
    ports:
      - "8089:8089"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  content-api:
    container_name: "fs-content-api"
    build: ../../../Images/CoreApis/ContentApi
    ports:
      - "8082:8082"
    networks:
      - fs_net
    volumes:
      - content:/app/content
    depends_on:
      mysql:
        condition: service_healthy

  chums-app:
    container_name: "fs-chums-app"
    tty: true
    build: ../../../Images/Chums/ChumsApp
    ports:
      - "3101:3101"
    networks:
      - fs_net

  b1-app:
    container_name: "fs-b1-app"
    tty: true
    build: ../../../Images/B1/B1App
    ports:
      - "3301:3301"
    networks:
      - fs_net

  lessons-app:
    container_name: "fs-lessons-app"
    tty: true
    build: ../../../Images/Lessons/LessonsApp
    ports:
      - "3501:3501"
    networks:
      - fs_net

  content:
    container_name: "fs-content"
    tty: true
    build: ../../../Images/NGINX/Content
    ports:
      - "3402:3402"
    networks:
      - fs_net
    volumes:
      - content:/content

networks:
  fs_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24
volumes:
  mysql_data_fs:
    {

    }
  content:
    {

    }
