CREATE DATABASE IF NOT EXISTS access DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS attendance DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS membership DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS giving DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS messaging DEFAULT CHARACTER SET utf8mb4;

CREATE DATABASE IF NOT EXISTS streamingLive DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS b1 DEFAULT CHARACTER SET utf8mb4;