CREATE DATABASE IF NOT EXISTS access;
CREATE DATABASE IF NOT EXISTS attendance;
CREATE DATABASE IF NOT EXISTS membership;
CREATE DATABASE IF NOT EXISTS giving;
CREATE DATABASE IF NOT EXISTS messaging;

CREATE DATABASE IF NOT EXISTS streaminglive;
CREATE DATABASE IF NOT EXISTS b1;