CREATE DATABASE IF NOT EXISTS attendance DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS membership DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS giving DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS doing DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS content DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS reporting DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS lessons DEFAULT CHARACTER SET utf8mb4;